services:
  db:
    image: postgres:16-alpine
    container_name: sokdak-core-db-dev
    env_file:
      - .env.dev
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - pgdata-dev:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: sokdak-redis-dev
    ports:
      - "6380:6379"
    volumes:
      - redis-dev:/data
    command: redis-server --appendonly yes

  app:
    build: .
    image: sokdak-core-api
    container_name: sokdak-core-api-dev
    env_file:
      - .env.dev
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
      - redis

volumes:
  pgdata-dev:
  redis-dev: