services:
  db:
    image: postgres:16-alpine
    container_name: sokdak-core-db-prod
    env_file:
      - .env.prod
    volumes:
      - pgdata-prod:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: sokdak-redis-prod
    volumes:
      - redis-prod:/data
    command: redis-server --appendonly yes --requirepass ${REDIS_PASSWORD}

  app:
    build: .
    image: sokdak-core-api
    container_name: sokdak-core-api-prod
    env_file:
      - .env.prod
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
      - redis

volumes:
  pgdata-prod:
  redis-prod: