package com.sokdak.auth.adapter.inbound.api.exceptions

enum class ErrorCode {
    DUPLICATE_LOGIN_ID,
    DUPLICATE_EMAIL,
    INVALID_PASSWORD,
    USER_NOT_FOUND,
    INVALID_CREDENTIALS,
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    EMAIL_NOT_VERIFIED,
    VERIFICATION_TOKEN_NOT_FOUND,
    VERIFICATION_TOKEN_EXPIRED,
    EMAIL_ALREADY_VERIFIED,
    EMAIL_SEND_FAILED,
}
